name: Test Code
run-name: Running tests on behalf of ${{ github.actor }} 🚀
on: [push]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
            node-version: 21.7.0
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: npm install
      - run: npm test -- --watchAll=false --passWithNoTests
